"""remove denormalized username column from auth_cookies

Revision ID: ac3f8e358ae9
Revises: 7aed18e2d148
Create Date: 2026-07-27 21:27:50.253718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac3f8e358ae9'
down_revision: Union[str, Sequence[str], None] = '7aed18e2d148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_cookies_username'), table_name='auth_cookies')
    op.drop_constraint(op.f('auth_cookies_username_fkey'), 'auth_cookies', type_='foreignkey')
    op.drop_column('auth_cookies', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_cookies', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('auth_cookies_username_fkey'), 'auth_cookies', 'users', ['username'], ['username'], ondelete='CASCADE')
    op.create_index(op.f('ix_auth_cookies_username'), 'auth_cookies', ['username'], unique=False)
    # ### end Alembic commands ###
